### ISSUE TITLE
BMS Designer Extension for z/OS V1.0.1

### ISSUE THREAD

**Issue by dvag-Matthias-Rudolph** [NEORIS-ZDEVOPS/BMS-Designer#1]
Our mask definition (*. BMS) on the HOST start on line 1 and have 17 lines.
(see SIZE / POS)
The BMS designer starts counting in line 0 and thus has line 16 as the last line.
As a result, the last line is never displayed.
Is there a way to fix this problem in the configuration of the BMS designer?
![grafik](https://github.com/NEORIS-ZDEVOPS/BMS-Designer/assets/138503691/ebb500fc-ab34-491f-b8ba-4ea093f23d30)

**Comment by antonkc** [comment]
Greetings @dvag-Matthias-Rudolph ,

Version 1.1.2 was released. Among other changes, now it starts from index one instead of zero.

**Comment by dvag-Matthias-Rudolph** [comment]
Great, i'll try it out right away!

**Comment by dvag-Matthias-Rudolph** [comment]
Works as it should, 👍

**Comment by antonkc** [comment]
Great to know, thanks.

Sorry it took so long to notice the issues. I forgot to enable notifications.
