### ISSUE TITLE
question: where is the code?

### ISSUE THREAD

**Issue by ssamayoa** [NEORIS-ZDEVOPS/BMS-Designer#2]
question: where is the code?

**Comment by antonkc** [comment]
We are not following an open source policy. Our code is no published as of now.

**Comment by ssamayoa** [comment]
ACK.

Then, AFAIK, this project does not belongs here at github.

**Comment by antonkc** [comment]
Although Github's main use is indeed storing source code, it also features functionalities that allow it to do much more. There is little reason to prevent it from being used for other reasons.

I also have to say that I understand where you a coming from. I will try to make the fact more obvious to prevent wasting time of future visitors.

**Comment by FALLAI-Denis** [comment]
Hi,

NEORIS is not alone in using GitHub without making its source codes available.
The advantage of being visible on GitHub is to offer an opportunity to discuss, report problems or suggest improvements or new features.

Regards,
