### ISSUE TITLE
Installed, created a new BMS file but plugin is never activated

### ISSUE THREAD

**Issue by ssamayoa** [NEORIS-ZDEVOPS/BMS-Designer#3]
Installed, created a new BMS file but plugin is never activated.

Also tried from command pallete:

![2024-05-16 11_13_51-Visual Studio Code](https://github.com/NEORIS-ZDEVOPS/BMS-Designer/assets/3533547/d8485596-0cc7-4aaa-8dda-c56152a3debc)

Just in case I disabled "IBM Z Open Editor" but same result.

*VERSION INFORMATION*

BMS Designer Extension for z/OS v1.0.1
IBM Z Open Editor: v4.2.0
Zowe Explorer v2.15.4
Zowe Explorer Extension for FTP v2.15.4

VS CODE :
Version: 1.89.1 (user setup)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by antonkc** [comment]
Greetings @ssamayoa,
Sorry for the very late answer.

This issue highlighted multiple usability problems with the extension. We are working to deploy a version that just works better.

On the other hand, to resolve your issue you may try to execute the command "BMS Designed: Parse this BMS file" to activate the extension. Then "BMS Hierarchy" menu shall appear in the file explorer hierachy.
![image](https://github.com/user-attachments/assets/06f985cf-43a0-421b-b66b-febfda355730)

If you press "Design", it will open you current file in the screen designer view. You need to hover over the group for those buttons to appear.

**Comment by antonkc** [comment]
Version 1.1.2 was released today, this issue shouldn't be happening again.
