### ISSUE TITLE
Access to NEORIS / BMS-Designer technology

### ISSUE THREAD

**Issue by FALLAI-Denis** [NEORIS-ZDEVOPS/BMS-Designer#4]
Hi,

In the issue:
* #2 

you specified that the BMS-Designer extension was not Open Source, however it is not subject to a paid license for its use.

We have needs that are close to those addressed by the BMS-Designer extension:
* a BMS screen designer, but with specificities not managed by the extension (migration from non-100% BMS software)
* a report designer, with production of the associated management code, (editing system by "lines block" assembling line backgrounds, conditioned variable parts, and conditioning for triggering each "block")

Would it be feasible to sell your technology, with the necessary protections to limit its use to our own context?

Thanks.

**Comment by antonkc** [comment]
Greetings,

I cannot make this decision.

Please, contact me to my mail:
anton.kryukov@neoris.com

I will send you the contact to talk this through.

Best regards.
